### ISSUE TITLE
void variable java-mode-plus-map

### ISSUE THREAD

**Issue by johnbendi** [skeeto/ant-project-mode#1]
There was no  specific instruction about how to require ant-project-mode in my startup file. So I simply (require 'ant-project-mode) hoping it will call javadoc-lookup. But on startup emacs halts reporting the above error. 

I have tried looking in java-mode-plus.el for that variable but it's not defined there. Also I thought ant-project-mode was supposed to replace java-mode-plus so how come the reliance on java-mode-plus-map.

**Comment by skeeto** [comment]
Sorry, that was just an oversight when I made the rename. Obviously I have not actually made use of this since then. I believe 1ed8a46 fixes this. You can completely ignore java-mode-plus.
